-keep,allowoptimization,allowobfuscation class com.jaredrummler.android.colorpicker.**
-keep,allowoptimization,allowobfuscation class androidx.annotation.Nullable
-keep,allowoptimization,allowobfuscation class androidx.annotation.NonNull
-dontwarn sun.security.internal.spec.**
-dontwarn sun.security.provider.**
-dontwarn com.jaredrummler.android.colorpicker.**
-dontwarn javax.annotation.Nullable